### ISSUE TITLE
OpenVibe distorting timestamps

### ISSUE THREAD

**Issue by dmedine** [sccn/labstreaminglayer#100]
Recently I have been helping a group of undergrads here at UCSD synchronize EEG data from an Emotiv headset with SNAP markers for an experiment that they are designing. They are using the OpenVibe software to gather the Emotiv data and stream it via LSL.

What I've noticed is that the timestamps from OpenVibe are completely different than what I expect. For example, the first timestamp from my ground truth signal is 
`first_timestamp: '85947.684254074'`
but from OpenVibe it is
`first_timestamp: '167.9296875'`

I can only assume that OpenVibe is doing something funny. Zeroing out timestamps may work if all the streams are going through OpenVibe, but otherwise, this makes the time data useless. It seems like whatever they are doing to change the timestamps needs to be toggle-able.

**Comment by chkothe** [comment]
Agreed, having an option to not override timestamps with OpenViBE's stamps
would be great! I think the main reason why they're doing it that way is
that OpenViBE relies on markers being passed through the hardware in some
trigger channel (instead of being directly emitted into LSL from a stim
presentation app), and when you're doing it that way, then the marker
timestamps will be jittered (the same way the EEG timestamps are). Now we
have the ability to dejitter the EEG stream, but it won't dejitter the
marker stream, which is separate... we'd need to add a feature to allow
that in an easy way. Once we have that, then they could switch to using
LSL-native timestamps for everything.

**Comment by dmedine** [comment]
Chadwick sent me some code for making a standalone emotiv app. The opensource emotiv sdk seems to differ somewhat from the one referred to in the code and until I can rectify these differences I can do nothing, but when that gets sorted, I will write a full blown emotiv app in the usual lsl qt style.
