### ISSUE TITLE
Memory Leak in ReceiveStringMarkers -> inlet.pullsample(std::string ....)

### ISSUE THREAD

**Issue by mgrivich** [sccn/labstreaminglayer#121]
I'm using liblsl/project/vs2013/vs2013.sln ReceiveStringMarkers and SendStringMarkers on windows. I've seen the problem in linux too, so it is not  project or OS dependent. SendStringMarkers is not changed. I've changed RecieveStringMarkers to 

    #include "../../../include/lsl_cpp.h"
    #include <iostream>
    using namespace std;

    int main(int argc, char* argv[]) {
	try {

		// resolve the stream of interet
		cout << "Now resolving a marker stream..." << endl;
		vector<lsl::stream_info> results = lsl::resolve_stream("type","Markers");

		cout << "Here is what was resolved: " << endl;
		cout << results[0].as_xml() << endl;

		// make an inlet to get data from it
		cout << "Now creating the inlet..." << endl;
		lsl::stream_inlet inlet(results[0]);

		// start receiving & displaying the data
		while (true) {
			string sample;
			double timestamp = inlet.pull_sample(&sample,1, 0.0);
			if(timestamp != 0) cout << "got: " << sample << endl;
		}

	} catch(std::exception &e) {
		cerr << "Got an exception: " << e.what() << endl;
	}
	cout << "Press any key to exit. " << endl; cin.get();
	return 0;
    }

The only change is that I've added a timeout of zero to pull_sample and don't print if no data was received. Running this with a process monitor open, you can see the memory usage reaching for the stars. Most likely, every call leaks, but it is possible that it is only the calls with no data received. `inlet.pull_sample(char * ....) does not appear to have this problem. I'd rather Christian fixes this since the internals of LSL are still a bit opaque to me, but if he is not available, I'll look into it.

**Comment by chkothe** [comment]
Thanks for the report -- will look into it. What's the urgency level?

**Comment by mgrivich** [comment]
I can work around it with char *, so it is more of an annoyance and blemish than a crisis.

**Comment by chkothe** [comment]
Ok -- in any case. I definitely want to get it fixed sooner rather than
later.

**Comment by mgrivich** [comment]
Some more information: when using lsl_pull_sample_str in ReceiveStringMarkersC.c, you leak memory unless you free(cursample) after use. I'm guessing that the C++ wrapper neglects to do this. However, my understanding is this is not the proper behavior for the C function. That is, it should be up to the user to allocate a char * that is large enough and pass it to lsl_pull_sample_str. At least, this is the behavior for all the numeric functions.

**Comment by atom2626** [comment]
I'm not sure if it is the same problem, but my Matlab instance crashes when calling inlet.pull_sample();

I'm running the unmodified ReceiveStringMarkers.m example provided with LSL.

**Comment by xloem** [comment]
I looked into this issue a bit.  There's a handful of memory leaks following this pattern.

What's interesting is that these functions that are leaking are already outputing c++ std::strings which do not leak.  The boilerplate code for the C library copies all the bytes and puts them on the C heap.  The boilerplate code for the c++ header then copies them all again and puts them back on the c++ stack, never freeing the C heap because there is no C++ way to do that.

Some solutions:

1. Include <stdlib.h> in the c++ header file to free these values.  This is the most straightforward but pollutes the namespace of everybody using the header.  It doesn't resolve the issue of copying data three times just to return it.
2. Inside liblsl, place the values in thread local storage rather than mallocing new content on the heap.  There may be perhaps one fewer copy.  The rest of the library seems to ignore threads.
3. Upgrade the library to provide external C++ functions in the binary.  This removes all extra memory copies and produces the fastest code.  It is also the most work and slightly decreases the portability of the library; C++ binaries often need to be built with similar compiler versions to work together.

My preference is fix #2.  I'm ready to implement this and submit a patch.

**Comment by xloem** [comment]
Whoop: the issue with # 2 is that this will change the C api to no longer require free() and break backwards compatibility.  Maybe I'll make a pull request for # 1.

**Comment by xloem** [comment]
Oh my goodness, just ignore me for now, I don't understand the code or issue well yet.

**Comment by dmedine** [comment]
Finally got around to testing this PR and it seems to be as good as advertised. No more leakage when no result comes in. @xloem, can you please email me your actual name so that we can acknowledge your contribution (we are preparing an LSL paper currently)?

**Comment by dmedine** [comment]
dmedine at ucsd dot edu
