### ISSUE TITLE
lsl_resolve_bypred and lsl_resolve_byprop returning empty results

### ISSUE THREAD

**Issue by syedahmar** [sccn/labstreaminglayer#136]
Hi there, 
following on from the issue I am facing here (https://github.com/sccn/BCILAB/issues/27), the Matlab functions (lsl_resolve_bypred and lsl_resolve_byprop) which should allow me to read data from LSL are not working for me. I have a number of streams running on LSL (confirmed by labrecorder, listing all the streams).I am particularly interested in capturing the stream from openVibe so I use (  lsl_resolve_bypred(lib,'type=''openvibeSignal''')  ) but it returns an empty array. If I use lsl_resolve_all(lib), I do get all the streams listed...any pointers?
I am using Windows 7, 64 bit and Matlab R2015b

**Comment by syedahmar** [comment]
Following on from this, I have also tried resolving only a particular stream using the python functions. At the moment, the function pylsl.resolve_streams work fine, and returns all streams. However, if I switch to using pylsl.resolve_stream('type' , 'AudioCaptureWin') for example, it just doesn't work. This seems to suggest that I can't get a stream by property or predicate but the function to get all streams work..and this behaviour is the same whether I use Matlab or Python..

**Comment by cboulay** [comment]
David Medine recently merged a [pull request I made](https://github.com/sccn/labstreaminglayer/pull/133). This upgrade pylsl in some ways, but it also added a couple things that might help diagnose your problem.

First, it added a script that tests most of pylsl. Please try running LSL/liblsl-Python/examples/PerformanceTest.py and let me know what errors you get, if any.

One error I anticipate is a problem related to `lib.lsl_set_postprocessing`. If you get an error that this function doesn't exist in the library then that means the version of the lsl library you have on the search path is old. Try replacing liblsl32 (or 64).dll with the newest from the ftp.

**Comment by syedahmar** [comment]
@cboulay I tried running the PerformanceTest.py and for some reason, the file was not allowing me to import the variables "proc_clocksync","proc_dejitter", and "proc_monotonize" from pylsl and was giving me the error of unresolved import. This is despite me being able to see these variables declared in the pylsl file.  Anyway, thinking this might be an issue specific to my IDE (am using eclipse with pydev), I proceeded by redeclaring these variables again with the values in pylsl, in the PerformanceTest. I ran the file, and the error I got it indeed "function 'lsl_set_postprocessing' not found"..(let me try updating as you suggested, and I will see what happens then)

**Comment by syedahmar** [comment]
I tried a number of different folders from the FTP to see if there is a later version of liblsl64.dll (since I am on 64 bit), but the latest one that I see is the file from 10th September 2015, and the problem still persists. Is there another location with a newer and updated dll file?  (I have tried the ones listed in here: ftp://sccn.ucsd.edu/pub/software/LSL/SDK/ )

**Comment by syedahmar** [comment]
@cboulay Given that the problem is a missing function not packaged in the liblsl64.dll (because it is quite old), I went to the C++ source and this function is indeed present in the C++ code which is on github. So I downloaded the latest code, installed visual studio 2012, and cmake, and rebuild the project myself on the local machine. The dll file that was generated in the build directory, I renamed it to liblsl64.dll and used that for running the python code. Now, the missing function problem is gone, and the script "PerformanceTest.py" seems to run fine now, showing the following in console: 
"Beta outlet pushing signal with shape 3276,6 and Beta amp 20.0
Beta inlet retrieved 3276 samples.
Beta outlet pushing signal with shape 3276,6 and Beta amp 20.0
Beta inlet retrieved 3276 samples.
Beta outlet pushing signal with shape 3276,6 and Beta amp 20.0
Beta inlet retrieved 3276 samples.
Marker outlet pushing string: GoCue, Class 1, Target 1"
However, the original problem, which is that the streams can all be retrieved by the provided API works, but using any of the APIs for trying to get the streams by predicate or property still does not work (in either Matlab or using Python)

**Comment by cboulay** [comment]
I'm pretty sure one of the dll's on the ftp is the newest version but I'm glad you were able to build it.

PerformanceTest.py already made use of [`resolve_byprop`](https://github.com/sccn/labstreaminglayer/blob/master/LSL/liblsl-Python/examples/PerformanceTest.py#L146), which calls [`lsl_resolve_byprop`](https://github.com/sccn/labstreaminglayer/blob/master/LSL/liblsl-Python/pylsl/pylsl.py#L562-L566).

I also modified, pushed, and merged a change to PerformanceTest.py so it now also makes use of [`resolve_bypred`](https://github.com/sccn/labstreaminglayer/blob/master/LSL/liblsl-Python/examples/PerformanceTest.py#L256).

But the version of PerformanceTest.py you had did use resolve_byprop, and it worked for you, otherwise the script would have hung forever or crashed when trying to get one of the streams. So the solution now is to make sure that your Matlab LSL is using the latest DLL, and also to make sure that your resolver arguments are correct.

**Comment by syedahmar** [comment]
@cboulay I inspected the code of PerformanceTest, and I can see the function resolve_byprop being called. So I am almost sure that the problem is incorrect argument that I pass. I assumed that the stream name is the one listed in labrecorder but I was wrong it seems. And the reason I am thinking this because while the PerformanceTest script is running, I see a new entry in LabRecorder called "BetaGen", but I can see in the function that it is actually using "EEG" and similarly for type "Markers", the labrecorder shows GeneratedCentreOutMarkers. So indeed I have been using the wrong arguments...
But here is my question:
How do I find out what are the correct stream names? Its definitely not what is listed in the labrecorder..So for example, if I run OpenVibe, and say a VideoStream, and Keyboard stream, what are the correct stream names which I can use to acquire them using the lsl_resolve_byprop function..
Thank you very much for your help so far.

**Comment by syedahmar** [comment]
sorted.. So the conclusion is that I was using the wrong argument and now it all works...I found the correct stream names by importing all running streams in matlab and then creating corresponding inlets and inspecting the xml (e.g. inlet.info().as_xml  in Matlab)..
I can't believe this issue led me to install IDEs, rebuild but it was quite a decent amount of learning :)
So thank you very much and really appreciated @cboulay

**Comment by cboulay** [comment]
You're welcome.

By the way, now that you have the latest version of LSL, you may be interested in [its latest feature](https://github.com/sccn/labstreaminglayer/blob/master/LSL/liblsl/include/lsl_c.h#L684-L694), which I believe is not integrated into the Matlab plugin yet. If it's something that you think you need then please open an issue about it. Or, better yet, add it yourself then make a pull request.

**Comment by syedahmar** [comment]
thanks a lot, I will for now prefer getting the original timestamps and doing postprocessing myself, and once I am quite comfortable with the whole setup and more familiar with using BCIlab + LSL for my experiment, and have built the whole working system that I am planning to, I will then check this again...

**Comment by dmedine** [comment]
Just to clarify, the latest build of LSL is on the ftp, here:
ftp://sccn.ucsd.edu/pub/software/LSL/SDK/liblsl-C-C++-1.12.zip

The functions that you listed which were inaccessible via Chad's python 
wrapper are exactly those that differentiate this version from the last 
one, so this version of libls64.dll is needed there. Sounds like you are 
well on your way now, Ahmar, but I will leave it to you to close the 
issue. We definitely need put the new online sync functions into the 
matlab wrapper sooner rather than later.

**Comment by syedahmar** [comment]
Can you tell me what tools etc. do you use to create a matlab wrapper for the c++ classes? Or any pointers to relevant documentation? I can then have a go at it.

**Comment by dmedine** [comment]
That would be awesome!

I think the best way to get started would be to checkout the repository 
on git, make a branch and once completed submit a pull request. That is 
the usual cycle. You will have to run the python script get_deps.py to 
download all the binaries. However, since you already built them, you 
may just want to the copy liblslXX.dll into your LSL/liblsl-Matlab/bin 
folder. Running get_deps.py grabs all the binaries for all the wrappers 
and all the apps, which is a lot of stuff.

As far as documentation is concerned, I myself am not super familiar 
with making matlab wrappers so I was just going go in to the source code 
for the Matlab wrapper 
(https://github.com/sccn/labstreaminglayer/blob/master/LSL/liblsl-Matlab/mex), 
figure out the yoga of it all, then add the necessary code to 
incorporate the new stuff. Basically, I was just going to use the source 
code as the documentation. However, I'm sure there are many, many online 
guides for doing this.

It looks like the way to make a Matlab wrapper to a C library is that 
for every function you want to wrap, you need to make a new source code 
file. In this case it would be calledlsl_set_postprocessing.c. I would 
start by copying an existing file from the wrapper, renaming it and 
changing the stuff that's not boilerplate.

It's not much that needs to go in. There is a data structure called 
lsl_processing_options_t which sets the rules for how the inlet performs 
post processing time correction (the default is to do nothing). This 
structure is then passed to a 'member function' of the lsl_stream_inlet 
'object' (quotes used because this is C that looks like C++, but not 
truly object oriented) called lsl_set_postprocessing. The flags are 
integers that are powers of 2, so a bitwise OR operation will combine 
them into the integer that lsl_set_postprocessing wants. All this is 
documented very cleanly in the lsl C API 
(https://github.com/sccn/labstreaminglayer/blob/master/LSL/liblsl/include/lsl_c.h) 
lines 123-134 and 685-694. It might also be informative to look at the 
equivalent code in the C++ API 
(https://github.com/sccn/labstreaminglayer/blob/master/LSL/liblsl/include/lsl_cpp.h) 
lines 71-82 and 753-761.

I don't know what your level of C chops is, so if this is over your 
head, no worries. This is a pretty tough project for a beginning C 
programmer. It would be wonderful to have your contribution of course, 
but if it is too big a project, I or some one else in the gang will get 
around to it eventually.

**Comment by syedahmar** [comment]
@dmedine Thank you for the detailed response. Actually I have understood what you have said above. I have no prior experience of making a wrapper myself, but given time, I think I will do this at some point (assuming it has not been done by then). I will of course update accordingly if that happens soon enough :)

**Comment by syedahmar** [comment]
@dmedine Regarding this, I have a quick question regarding building a mex file in Matlab. From the documentation, I can see that one way to create a mex file is by using "mex filename" in command line in Matlab. So in this particular case,it would be "mex lsl_set_postprocessing.c" assuming that the actual computational routine was also inside the lsl_set_postprocessing.c ...But that isn't the case when we create these wrappers, and according to the documentation: 
_" If you write separate gateway and computational routines, you can combine them into one source file or into separate files. If you use separate files, the file containing mexFunction must be the first source file listed in the mex command._"
So I just want to know what is the file with the computational routine that I have to use for creating the mex file...(If you have done it differently, then that would mean that I am completely off track :)  )
