### ISSUE TITLE
Resolving EEG signals in Matlab background

### ISSUE THREAD

**Issue by GGGGFan** [sccn/labstreaminglayer#139]
Hi,

I'm trying to compute some EEG measures by Matlab in real time, which means the signal stream needs to be resolved in background and computation needs to be performed at the same time with the input streaming.  Since a shuffling process is involved in my computation, making a small chunk size to let it appear close to real time is not feasible.

I know LabStreamingLayer can collect signal but my problem is that when the signal is being collected by LSL, real time computation cannot be realized by Matlab (because Matlab is busy at data collection). Is there any method to resolve the EEG signal in Matlab background?

Thanks a lot,

Gfan

**Comment by dmedine** [comment]
Not the best solution in the world, but you can run two instances of 
Matlab and pipe the data from the data acquiring process and the data 
processing process. I forget exactly how one does this in Matlab, but 
I'm pretty sure it's doable. You can also launch threads in Matlab 
<http://www.mathworks.com/discovery/matlab-multicore.html>, which might 
be enough to get you what you need.

The other option is to use C/C++ or Python to do your computations 
(again with parallel processes for data grabbing and data manipulating). 
ScipPy, from what I understand, has pretty much everything Matlab has, 
but not necessarily all the toolboxes (which may be what you need in the 
first place).

I'm going to close this issue and forward it to the LSL list since it is 
a more appropriate question for that forum. You can subscribe here 
<https://mailman.ucsd.edu/mailman/listinfo/lsl-l>.
