### ISSUE TITLE
Unstable but predictable sampling rate - best practice?

### ISSUE THREAD

**Issue by Foucl** [sccn/labstreaminglayer#151]
I am using LSL to forward samples of a recording device (facial expression recognition software) generates samples at about 31.3 Hz so that usually a new sample is generated every 32 ms. However, exactly every 12th sample is delayed by 16 ms (so the timespan between the 12th and 13th, 24th and 25th etc sample is 48 ms instead). Is it enough to just set can_drop_samples to true or is there a better way to accomodate that in the stream settings?

**Comment by dmedine** [comment]
I presume this is coming from some kind of webcam? I've sen this kind of 
sampling irregularity before. If memory serves, I think that you don't 
even need to set can_drop_samples in order to smooth out this 
irregularity. It should be that the normal time smoothing routines in 
load_xdf can handle what you describe. I would recommend testing all 
configurations before coming to a final conclusion. You can edit an XDF 
post-recording with XZDFBrowser. Also, you can load the XDF with 
HandleJitterRemoval set to false. This will prevent both jitter removal 
and, if present, the can_drop_samples routine is triggered by the flag 
in the XDF from happening.

**Comment by Foucl** [comment]
yes, it's a logitech webcam that is connected to a PC running iMotion's Facial Expression Recognition Module. It seems impossible to fix the webcam's framerate (at least on Windows and with the official drivers).
thank you for your suggestions - I hadn't thought about testing using the XDFBrowser. If it's alright, I'll close this issue and post the results of my testing as soon as I get to it.
