### ISSUE TITLE
pylsl: Deleting an Outlet Crashes Python

### ISSUE THREAD

**Issue by Foucl** [sccn/labstreaminglayer#154]
While dealing with #142, I discovered that trying to delete an outlet reliably crashes python.exe using the latest liblsl64.dll from the ftp repository  (liblsl-C-C++-1.12.zip, library_version: 112, protocol_version: 110). I built the dll myself using Visual Studio 2013 Community Edition from the HEAD of this git repository, and using the resulting .dll, those crashes do no longer happen.

My Environment is Windows 7, 64 bit, Anaconda x64, Python 2.7.

Minimal Example resulting in the crash:

```python
import pylsl
import time
info = pylsl.StreamInfo("test_stream", 'Markers', 1, 0, 'string', 'testid')
outlet = pylsl.StreamOutlet(info)
time.sleep(1)
del outlet
```

Deleting outlets is an important feature for me because otherwise streams will linger in the network until the python session where the outlet was created is killed/restarted. This would lead to a lot of duplicate streams as seen by LabRecorder and in the resulting .xdf.

This issue is probably not necessary, as cboulay already [commented](https://github.com/sccn/labstreaminglayer/issues/142#issuecomment-254063749) on the fact that the liblsl in the ftp repository is outdated. So this could be closed and serve as a reference for whoever is facing the same issues as me.

[Edit] Added Info about Python Environment

**Comment by cboulay** [comment]
Actually my comment was about pylsl.py. I thought the compiled library on the FTP was up-to-date. There are a couple delete-related changes since the last official build so maybe you're still right. I think after @dmedine makes the next official build you should test it for this error, because it might be something specific to his vs your build systems.

**Comment by dmedine** [comment]
Slow I am to catch up on all of this, but, yes the library on the FTP is totally up to date. I was not aware about pylsl. I will push the latest version up to the FTP. I also noticed that the liblsl-Matlab on the FTP is actually an archive of the python wrapper. I added a mexmaci64 build to that the other day, so I will make that correction as well.

**Comment by dmedine** [comment]
Done.

**Comment by Foucl** [comment]
thanks @dmedine. the problem with liblsl64.dll remains (deleting an outlet through pylsl fails (crashes python) with the dll from the ftp server and succeeds with the one I built myself). Or did I miss the update to liblsl on the ftp server?

**Comment by dmedine** [comment]
Well, indeed I get the same error with the liblsl64.dll from the ftp. Curiously, I get the crash when I run your code, but not when I  send a few samples first:
`import pylsl
import time
from random import random as rand
info = pylsl.StreamInfo("test_stream", 'Markers', 1, 0, 'string', 'testid')
outlet = pylsl.StreamOutlet(info)
for n in range(1,100):
    mysample = ['lala']
    # now send it and wait for a bit
    outlet.push_sample(mysample)
    time.sleep(0.01)
time.sleep(1)
del outlet`

In any case, I am recompiling the library and will test and push it to the ftp so that everything works.
