### ISSUE TITLE
Contribution guidelines

### ISSUE THREAD

**Issue by tstenner** [sccn/labstreaminglayer#203]
I'm currently working on some improvements for the BrainAmp App and when it's ready I'd like to submit a pull request. Many other projects have [contributing guidelines](https://github.com/blog/1184-contributing-guidelines) that answer the common questions.
I've already found the build instructions, but I think there are some guidelines that should be "set in stone", like:

- Formatting guidelines for new code (ideally as [clang format](https://clang.llvm.org/docs/ClangFormatStyleOptions.html) file, the [clang format configurator](https://zed0.co.uk/clang-format-configurator/) is pretty useful in choosing a style).
- minimum supported compilers / OSes. I read somewhere that VS2008 is the oldest supported compiler for liblslm, but especially for some apps targetting C++11 (e.g. for `std::thread`, `std::chrono`, `std::regex`) instead of Boost might make sense
- minimum requirements for documentation / comments.

**Comment by dmedine** [comment]
As of now, I am disinclined to impose and coding guidelines, but if people feel very strongly about this, please speak up. The main reason is that the apps and wrappers have so much variety in terms of languages, IDEs, etc. that to construct robust, meaningful coding guidelines is a rather large task. But, let me try to answer your three questions as best I can.

-Personally, I don't really care about formatting. I shift between different styles all the time depending on what IDE I'm using, and whether it is C or C++. In general I am totally agnostic. As long as it's clean and fairly consistent, I don't much care. Some rules of thumb that I try to follow are 1. Try not to make any function so long that you need to scroll through it (this is impossible for certain boilerplate functions in LSL apps) and 2. comments should explain 'why' the code is written the way it is, not 'what' it means. What it means should be self-evident from the code itself (again, sometimes this is not practical).

-As far as compilers are concerned, liblsl is written to be compatible with pretty much all of them (older than C++ 11), but this is not so for the apps. For most of them, linux and Mac are irrelevant since the devices (e.g. BrainAmp) need Windows to run. Also, nearly all the apps are Visual Studio based projects anyway, so I don't see much sense in supporting, say, the Borland compiler. Visual Studio 2008 is adhered to since some people are still using XP in their labs for special devices or whatever. In the end, there is no escape from boost for liblsl since it relies so heavily on boost::asio. However, this is not the case for the apps. It is a pain to install boost, etc., but in the end (if I'm not mistaken) things like std::thread, std::chrono, and std::regex, are actually their corresponding boost libraries. Since boost is so ubiquitous, I don't see much payoff for switching away from it. So, the short answer to question 2 is VC90, or (if necessary) VC100.

-Again, I'm not sure how to sculpt a meaningful set of guidelines to specify documentation. Most of the apps are pretty much completely self-explanatory and as such have meaningless, and even false README files. I would say, make a README and use your best judgement about what to include. If there is a 'gotcha' in there, be sure to include it. For comments, please see my comment above.

In any case, I am sorry to say that unless this becomes a much more requested feature, I don't want to spend any time actually thinking about the right way to do this. Of course, if anybody else has an actual opinion, or wants to do it, I'm open to discussing it.

**Comment by tstenner** [comment]
Thanks for your detailed answer. I can understand writing a set of guidelines is a lot of work for no big gain, so I'd try to make it as easy as possible to have a consistent style.
I could add presets (for clang-format, Qt Creator and Visual Studio). Using them could be optional, but those who want a consistent style can import them and have the formatting done by the IDE. If it's ok for you, I'd create those over the weekend and make a pull request.

Regarding the compiler support I agree as far as liblsl is concerned. For the apps, I see several advantages in having a more recent compiler:

- even VS2017 runs on Windows 7 SP1 and supports targeting Windows XP (as long as the Visual C++ Redistributable Package is installed)
- the [Visual C++ 2015 and 2017 compilers](http://landinghub.visualstudio.com/visual-cpp-build-tools) can be installed without Visual Studio
- Apps that only need libraries already in the standard runtime could be compiled without having to install Boost, configure the installation directory, bundle the libs if linking to shared libraries and so on.
- several newer C++ features prevent mistakes (e.g. `auto`, range-based `for`-loops)
- [AppVeyor](https://www.appveyor.com/) offers free builds and test runs for open source projects, but only offers [Visual Studio 2013 or later](https://www.appveyor.com/docs/build-environment/)

Again, I understand it's work you could be spending on more important things, so I'd set this up for myself (and maybe @cboulay? He seems to have similar goals with his CMake work) first and hope the results convince you :-)

**Comment by cboulay** [comment]
I definitely perceive liblsl development and LSL-App development to be two distinct things. Very few people are actually going to touch liblsl code so style guidelines won't have much benefit there. Style guidelines will have more benefit for the Apps, where there are more people contributing, but many such people (like myself) are neuroscientists who will hack away at some code first and look for style guidelines later (or never). If the option is available then a gentle reminder might help, but I don't think acceptance of a PR for a new app should require it because then we might just end up with fewer Apps.

I'm all for abandoning any requirements for old Visual Studio for any Apps. I've also been trying to eliminate Boost as a dependency for my apps, replacing it with STL as much as possible and sometimes Qt (because Qt is needed anyway for the GUI-based apps). I'm also not a big fan of providing IDE-specific project files; I use 4-5 different computers running Ubuntu, MacOS, or Windows 10 with slightly different folder structures. A vsproj file I make on one computer is often useless even on another one of my own computers, let alone on the computer of someone at another lab on the other side of the world, so I prefer CMake. In other words, I'm agnostic as to which versions of Visual C++ should be supported but I'm not going to go through hoops to support older versions.

@dmedine previously mentioned that building and maintaining the Apps on the ftp is too much of a burden and may soon become impossible (due to access restrictions). AppVeyor might be the solution and I think abandoning old Visual Studio versions is an acceptable trade-off.

**Comment by dmedine** [comment]
I'm inclined to agree with cboulay about CMake. I think if any overhaul is to be made for the apps build process it should be done there. Unfortunately, going through each project and replacing all the vcproj files with CMake (or anything, for that matter), eliminating boost dependencies etc. is just a ton of work. The only way I would want to do that would be to have a day long meetup/hackfest that involves copious amounts of beer and loud dance music. This _should_ happen, though. If LSL had funding, we could organize such an event. Maybe if there is another LSL meeting we could put something like this on the agenda.

For now, I think a reasonable policy is to be more modern (i.e. C++ 11 and even Qt 4, which I think cboulay is already using) in new developments. That way, we can try out a few different options and figure out what is the best strategy. Once that is solidified, a complete overhaul is just busy work (hence the need for beer and dance music).

As for AppVeyor, it looks very interesting but I hesitate to go down that road for two reasons. The first is that although 90% of the apps target only Windows, several do not and several are written in python. I think it is unwise to have more than one repository for the Apps. The second is that it might go away. This happened with google code, which originally hosted LSL and it was not fun moving to github (although, I do like github more).

**Comment by tstenner** [comment]
I'm currently converting the BrainAmpSeries App to CMake (using @cboulay's CMakeLists.txt for LabRecorder as an example) and even though there are still some things to be done, it's much easier than anticipated. Once it's done, it's just a matter of copying the file to another folder, replace some Qt4 in the source code with Qt5 and delete the VC project files (so definitely possible in a day with beer + dance music).

Regarding AppVeyor it also has Python preinstalled, so building python apps is certainly possible. It could go away, but the configuration file is just a collection of build scripts (about 26 lines at the moment) with almost everything important in the CMake files. Replacing it with a local build service (we need for Linux/OS X apps anyway) involves installing the build environment (VC, Boost, Qt, ...) somewhere and calling the build script from time to time.

**Comment by dmedine** [comment]
The problem with AppVeyor (or any service) disappearing in my mind is not the inconvenience of moving or restructuring, but rather having binaries available in more than one location for download. On the other hand, it would be a lot easier to simply have the latest source code build behind the cloud so that users can always get the latest version.

**Comment by dmedine** [comment]
Regarding the CMake process, once you've finished your work on the brainamp, I will take a look at it and see how feasible it is to make the switch. It might be somethig that we should just go ahead and pull the trigger on.

**Comment by dmedine** [comment]
@tstenner  in light of your most valuable contribution to the project, we would like to invite you to be a contributor for LSL (i.e. have commit privileges). My work email is online anyway so I don't mind posting it: David.Medine@brainproducts.com. Drop me a line and will give you my private address.
