### ISSUE TITLE
socket_utils.h: error: no member named 'cerr' in namespace 'std'

### ISSUE THREAD

**Issue by cboulay** [sccn/labstreaminglayer#218]
It appears there's a problem with Mac compilation with some compilers / versions of the STL, first reported by @hannahlef [here](https://github.com/sccn/labstreaminglayer/pull/147#issuecomment-327890730). The simple solution is to add `#include <iostream>` to the include list in socket_utils.h.

I am also running MacOS Sierra but do not encounter this problem. Maybe we have different versions of Xcode. Anyway, this should be a simple fix that will be innocuous for unaffected platforms, but I am inviting comments before I touch the core library.

**Comment by dmedine** [comment]
I seem to remember having to surgically reorder included headers back 
when I compiled liblsl for iOS. CLang/XCode get pretty touchy about 
that. I don't /think/ this will break anything, but let's try compiling 
liblsl on Linux and Windows with this patch before merging it. I will 
try it on Windows today.

**Comment by hannahlef** [comment]
My version of Xcode is 8.3.3.

**Comment by hannahlef** [comment]
My version of Xcode is 8.3.3.

**Comment by tstenner** [comment]
The CI says: [Windows works](https://ci.appveyor.com/project/tstenner/labstreaminglayer/build/1.40.0.36), [Linux works](https://travis-ci.org/tstenner/labstreaminglayer/jobs/289996032) and [OS X fails due to a problem with Travis](https://travis-ci.org/tstenner/labstreaminglayer/jobs/289996033).
I've also tried this fix on a different Windows machine, so there should be no harm in merging it.
