### ISSUE TITLE
Matlab/Mex: crashes with unmangled Boost symbols

### ISSUE THREAD

**Issue by tstenner** [sccn/labstreaminglayer#227]
Matlab ships its own Boost libraries, so loading a shared library with a different Boost version causes Matlab to crash. This hasn't been a huge problem before, as the distributed shared libraries were built with lslboost, but the `loadlib`-routine should somehow detect this.

**Comment by dmedine** [comment]
I think that the only way to do this is to insert a function in the 
source code of the core library that reports the boost version and then 
have loadlib call that. However, if it crashes on the load itself, this 
wouldn't work.

**Comment by tstenner** [comment]
This might work, since the crash appears only in functions that use Boost:
<pre><code>>>lib = lsl_loadlib();
a=lsl_library_version(lib)
a = 112
>> info = lsl_streaminfo(lib,'ABC,'DEF',5,0,'cf_float32','sdfwerr32432');
------------------------------------------------------------------------
       Segmentation violation detected
------------------------------------------------------------------------
[..]
Stack Trace (from fault):
[  0] 0x00007f09aa999866 /matlab/bin/glnxa64/libboost_filesystem.so.1.56.0+00047206 _ZN5boost10filesystem6detail15system_completeERKNS0_4pathEPNS_6system10error_codeE+00000038</code></pre>

**Comment by mgrivich** [comment]
I'm all for more error checking. But why did we run into this problem? 
Is someone building LSL with non lslboost? That isn't a very good idea. 
Aside from namespace collisions like this, I remember David once changed 
boost versions and ran into subtle changes in timing behavior.

I'd actually recommend that a compile time error if a user tries to 
compile LSL with non lslboost.

**Comment by cboulay** [comment]
The option to compile LSL with system boost was in the cmake files long before @tstenner and I ever touched them. Should this option be removed?

Are there any platforms where lslboost will not work? I know I've had better success compiling LSL with system boost in Linux and Mac but I never hunted down why it didn't work with lslboost.

Do we expect lslboost to stop working at any point in the future when using newer compilers and STLs? If I remember the warnings correctly, I think lslboost is already using some to-be-deprecated features.

The forward-looking solution instead might be to remove the lslboost dependency and fix whatever is preventing us from using regular boost outright. I know that's not a small task and will require some changes to the core library, and @chkothe will likely have to get involved, but I think it has to be done eventually.

**Comment by tstenner** [comment]
Well, I ran into this problem because lslboost doubles compile times on a clean build and produces a lot of compiler warnings and so I used the system boost libraries for test builds. I couldn't find the timing problems in the issue tracker, do you have a link for that?

There are several cases where the system boost libraries are not an option (this being one of them), but to keep LSL working on new platforms not yet supported by lslboost we need to test with other boost versions.

**Comment by mgrivich** [comment]
On 9/27/2017 7:42 AM, Chadwick Boulay wrote:
>
> The option to compile LSL with system boost was in the cmake files 
> long before @tstenner <https://github.com/tstenner> and I ever touched 
> them. Should this option be removed?
>
I'd say yes. Or it should have a very large warning label.
>
> Are there any platforms where lslboost will not work? I know I've had 
> better success compiling LSL with system boost in Linux and Mac but I 
> never hunted down why it didn't work with lslboost.
>
I've never had any problems using LSL boost on mac (XCode) and linux 
(code.block). I can get it working with CMake if you need assistance.
>
> Do we expect lslboost to stop working at any point in the future when 
> using newer compilers and STLs? If I remember the warnings correctly, 
> I think lslboost is already using some to-be-deprecated features.
>
Generally when lsl boost has a problem, the safest thing is to back port 
the specific lines of code from a later version of boost. I've done this 
several times.
>
> The forward-looking solution instead might be to remove the lslboost 
> dependency and fix whatever is preventing us from using regular boost 
> outright. I know that's not a small task and will require some changes 
> to the core library, and @chkothe <https://github.com/chkothe> will 
> likely have to get involved, but I think it has to be done eventually.
>
Boost itself is a monstrosity, that we only use because we must. Keeping 
it contained in our own branch is the safest way to go. If we are going 
to push for an update, it should be to remove as many boost features as 
possible from the core library. However, that is a large and dangerous 
project, which is why we haven't done it yet.

**Comment by mgrivich** [comment]
lslboost has worked on every platform I've tried. If it fails to build 
in a specific scenario, let me know and I will fix it.

**Comment by mgrivich** [comment]
Below is the original message from David regarding the problems with 
changing boost versions, to jog everyone's memory.



-------- Forwarded Message --------
Subject: 	Re: failure to replicate LSL validation experiment
Date: 	Fri, 8 Jul 2016 11:08:09 -0700
From: 	David Medine <dmedine@ucsd.edu>
To: 	Christian Kothe <christiankothe@gmail.com>, Matthew Grivich 
<matthew_grivich@neurobs.com>



Actually, it turns out that boost is the culprit! I am still making the 
figures, but it looks like the lag (all other things being equal) when I 
link against boost v.1.57 is 2.7 ms (total, not in addition to the 
7.72ms figure Matthew and I have seen in the past). When I link against 
1.60, it is much higher, ~12ms.

I will send along some preliminary figures when I am done catching the data.
-David

**Comment by tstenner** [comment]
Thanks for the mails, I reformatted it so the last parts are more readable.
As for the CMake build we could hide the `LSL_USE_SYSTEM_BOOST` option and put a warning comment above the code that checks for it and changes the imports.

-------- Forwarded Message --------
Subject: 	Re: failure to replicate LSL validation experiment
Date: 	Fri, 8 Jul 2016 11:08:09 -0700
From: 	David Medine <dmedine@ucsd.edu>
To: 	Christian Kothe <christiankothe@gmail.com>, Matthew Grivich
<matthew_grivich@neurobs.com>



Actually, it turns out that boost is the culprit! I am still making the
figures, but it looks like the lag (all other things being equal) when I
link against boost v.1.57 is 2.7 ms (total, not in addition to the
7.72ms figure Matthew and I have seen in the past). When I link against
1.60, it is much higher, ~12ms.

I will send along some preliminary figures when I am done catching the data.
-David

On 7/8/2016 10:38 AM, Christian Kothe wrote:> Hi folks,
> 
> that's quite interesting, especially considering that the 
> time-stamping is happening before anything is being sent through
> liblsl.
> 
> There is one change that I could imagine having something to do with 
> it, and that's that the newer liblsl versions reduce the Windows 
> time-slice resolution from default 4ms to 1ms to improve throughput 
> and reduce random fluctuations in transmission time down to the
> levels seen on other platforms (Chrome and some other apps like game
> engines do that too). This in turn could potentially have affected
> the internal latency of the Biosemi driver (though one would expect
> it to be reduced).
> 
> We could test whether that's the reason by overriding liblsl config 
> value to what it was before (it's configurable). Now if that's in
> fact the reason, then I would suggest keeping the new setting,
> because the actual time-slice resolution that Windows will use is the
> minimum of those requested by any of the running applications (cf. 
> timeBeginPeriod / timeEndPeriod
> <https://msdn.microsoft.com/en-us/library/windows/desktop/dd757624%28v=vs.85%29.aspx>),

> and since 1ms is the lowest, you get the same behavior and timings 
> regardless of what other apps may or may not run at the same time
> and request time-slice reductions.
> 
> Christian
> 
> On Fri, Jul 8, 2016 at 9:52 AM, Matthew Grivich 
> <matthew_grivich@neurobs.com <mailto:matthew_grivich@neurobs.com>>
> wrote:
> 
>> Christian might just know what the issue is, since he makes the 
>> majority of the edits. Otherwise, the best way to figure it out is 
>> typically to get the last good version and the first bad version 
>> and run them through a code comparison tool such as Beyond Compare.
>> You can then add changes one by one to see which the critical
>> change was. I really doubt that it is the compiler.
> 
>> Of course, this isn't technically a bug, so we may decide to 
>> document the change, adjust the default offset in the biosemi app, 
>> and move on. Of course, this should happen after we know exactly 
>> what the issue is. It may reoccur "randomly" if we don't know the 
>> cause.
> 
>> On Thu, Jul 7, 2016 at 6:11 PM, David Medine <dmedine@ucsd.edu

**Comment by dmedine** [comment]
So, yes, changing versions of boost does change latencies for some 
unknown reason. However, in my experience, so does changing operating 
system and hard drive type and a million other details. In short, 
latencies should be checked and re-checked all the time.

I don't know why Christian didn't pick out the parts of boost that he 
needed instead of grabbing the whole damn package. This does indeed slow 
things down quite a bit. Plus, if one wants to use an updated version of 
boost, one has to lsl-ize it with a python script. I think it would be 
awesome to trim this down, but as Matthew notes, it is a big, bad job. I 
certainly don't have the time or wherewithal to take it on...

I think the main components are from asio, algorithm, and threading 
packages.

**Comment by tstenner** [comment]
[Boost BCP](www.boost.org/doc/libs/release/tools/bcp/doc/html/index.html) can do exactly that.

`bcp --boost=/tmp/boost_xy --namespace=lslboost --namespace-alias --scan LSL/liblsl/src/*.h LSL/liblsl/src/*.cpp lslboost/` will scan all files for boost includes, take almost only these headers from `/tmp/boost_xy` (and all files they depend on), rename the symbols to `lslboost` and optionally (`--namespace-alias`) make them accessible as the old symbol names, so in the code `boost::XY` stil works, but the symbol name is `lslboost::XY`.

To get back to the topic: for shared libraries that can't contain boost symbols, we can depend on a lslboost symbol, so linking to LSL compiled with system boost fails at link time or try to resolve it at run time and return a helpful error message.

**Comment by mgrivich** [comment]
Umm. He did pick out the parts of boost that we use. That is what lsl 
boost is. As Tristan says, BCP can be used to generate libraries like 
lsl boost. And BCP is almost certainly what Christian used to generate 
it. If you are downloading / installing / linking any boost files / 
libraries except what is on github at 
https://github.com/sccn/labstreaminglayer/tree/master/LSL/liblsl/external 
you are making extra work for yourself.

Of course, this is referring to building the core library. Apps or 
extensions may do other things. I haven't compiled them recently.

**Comment by mgrivich** [comment]
I hesitate to say exactly how you should handle the CMake build, since I 
haven't gone over it carefully. However, I'm not a fan of hidden 
options. If you still feel the need to keep the option, I'd say to keep 
it visible, but with a very obvious warning label (preferably in the 
documentation and during compile time).

**Comment by dmedine** [comment]
Doh! I misunderstood. I've never actually looked at lslboost and I 
assumed that since it was slowing down the compile time so much that it 
was more than just a few libraries. There I go, half-cocked as usual.

I think that it would be good to have the option to update lslboost. 
There is a python script that does the dirty work. I still know nothing 
of CMake. Can one call that from the build process itself or does it 
have to be an extra step?

I have more time to work on LSL at the office now, so hopefully now I 
can contribute more than mere hearsay as time goes on.

**Comment by dmedine** [comment]
I've been looking into this a little more carefully now. I'm actually not sure that Christian used bcp at any point. It looks to me like he just copied all the headers in /boost along with all the subdirectories he needed and then mangles the names. Then, a subset of those libraries get aliased to the 'boost' namespace.  The pyhon script https://github.com/sccn/labstreaminglayer/blob/master/LSL/liblsl/external/premangle_boost.py does the actual work. 

There are two things that I don't understand. One is why Christian chose to do this rather than to use bcp. The other is why only a subset of the mangled libraries get aliased to the 'boost' namespace (which might actually be the answer to the first question).

I propose that we develop the python script so that it is more robust. In particular, one should be able to choose a 'system' boost to copy in the 'external' directory where it stays, mangled appropriately. This is not a big task. Then, I propose removing the option to link LSL to system boost altogether. If I understand correctly, this will forever squash the problem that @tstenner is having with Matlab, or any other boost client. I'd be happy to do this. Please post any objections or suggestions.

As far as deprecation goes, I don't think we have too much to worry about there. We can cross those bridges as they come.

**Comment by tstenner** [comment]
I've also thought about it a bit and come to the same conclusion. Linking LSL as a shared library to the apps means that the apps need to be compiled with the same boost version as LSL itself.
Removing the support for unmangled Boost should include removing the compability headers, so instead of `#include <boost/xy>` / `boost::xy` the could directly uses `#include <lslboost/xy>` / `lslboost::xy`. Also there's no more mucking around with Boost.build / b2 / bjam on Windows :-)

Instead of the python script I'll take a look if bcp can rename the symbols right. It's not perfect (it doesn't parse `#ifdef`s), but it filters out the needed headers, so including another boost header and running bcp should just work.

The transition would look as follow:
1. I change the includes and names to use lslboost directly.
2. Instead of `LSL_USE_SYSTEM_BOOST` the option becomes `LSL_LSLBOOST_PATH` to use an updated version of lslboost for testing. Maybe this could also print out a warning that this is not supported.
3. I'll try to reproduce the timing issues with a newer boost version.

**Comment by dmedine** [comment]
I'd be curious to see how bcp stands up. I didn't try just because I was 
too lazy to compile it (always such a drag on windows...). But, as I 
say, adding some features to the python script is trivial.

**Comment by tstenner** [comment]
Quick update: bcp doesn't rename the include directories, but shrinks the boost files down to 28MB.
A quick test with 10000 samples (`push_sample` with `pushthrough=true´ and `pull_sample`) in the same process shows a mean latency of 1.36ms (SD=.497) with the normal lslboost and 1.31ms (SD=.491) with a renamed boost 1.65.1.

**Comment by mgrivich** [comment]
With these tests, I think it may be a good time to replace lsl boost 
with an updated (1.65) version. I prefer using bcp rather than 
Christian's homegrown name mangler. A new branch should be created, and 
then the branch should be heavily tested before merging to master. Who 
would like to take lead on this? I can, but it seems we do not have a 
shortage of volunteers, and I'm content to take a testing and code 
reviewer role.

**Comment by tstenner** [comment]
I wouldn't be too optimistic as I could only test this on linux (which, according to Mario Kleiner of Psychtoolbox fame is the least problematic system) and it only tests a small part (instantly pushing and pulling samples). Still, it's a start.
I'll create a PR and keep it up to date, but we need a whole bunch of testers for this.

**Comment by mgrivich** [comment]
Okay. I thought your test was a bit more thorough. In that case, I'll 
think about it some more, and put some time into it when I have more 
availability. It could be up to a month. I do have access to all three 
main OSes. Don't take Mario too seriously. He has irrational biases 
against Windows and Linux. All three OSes are good enough. None off them 
are as good as we would like.

**Comment by tstenner** [comment]
On Windows I get the following numbers:

Old lslboost: 2.06±0.330
Boost 1.65.1: 13.5±8.02

**Comment by mgrivich** [comment]
Thanks for testing this. It looks like we need to stay with old lsl 
boost. Live performance is much more important than compilation time.

**Comment by tstenner** [comment]
Well, I've found the first problematic version. At least 1.65 got better.
<pre>                           0%       25%       50%       75%      100%
bounce_lslboost.csv 1.0584400  1.988093  2.003653  2.015903  4.036441
bounce_1_55.csv     1.0687030  1.987431  2.001998  2.014910  4.033130
bounce_1_56.csv     1.0422170  1.985444  2.003322  2.021862  4.037434
bounce_1_57.csv     1.0385760  1.986437  2.002660  2.020538  4.060609
bounce_1_58.csv     0.9673949 13.200124 23.034396 27.025313 53.808282
bounce_1_58_pt2.csv 0.9710371 13.020268 23.050453 27.203514 53.581828
bounce_1_60.csv     0.9581250 13.171652 23.020325 27.025893 53.786762
bounce_1_65_1.csv   0.9475300  7.174184 12.002716 19.008301 53.291808</pre>

**Comment by tstenner** [comment]
<pre>                   0%      25%      50%      75%    100%
lslboost     1.058440  1.98809  2.00365  2.01590  4.0364
1.58         0.967395 13.20012 23.03440 27.02531 53.8083
1.65.1       0.947530  7.17418 12.00272 19.00830 53.2918
1.65.1+yield 0.008938  0.01953  0.02913  0.03443  0.2155</pre>

The culprit seems to be `boost::this_thread::sleep()`. In 1.58, it changed the default behavior on windows to sleep for the requested time plus 32ms ([bug report](https://svn.boost.org/trac10/ticket/11331)). So whenever the receive queue is empty, there's a potentially long waiting period.
Replacing the `sleep()` call with `yield()` yields a median latency of 29ms (range 0.9-216ms). This isn't very processorfriendly, but if this is the source of the problem we could either apply a patch to a recent boost version, use a windows-specific workaround for sleeping threads or use a condition variable.

 @mgrivich if you still have the equipment of your previous tests I could compile three versions (lslboost, 1.65.1 and patched 1.65.1) for you to test.

**Comment by mgrivich** [comment]
Do you mean 29 microseconds (usually abbreviated 29 us is ascii text)?

**Comment by tstenner** [comment]
My bad, I'm more used to larger durations. I corrected it in the text.

**Comment by tstenner** [comment]
Moved to https://github.com/labstreaminglayer/liblsl/pull/4
