### ISSUE TITLE
CMake questions for liveamp update

### ISSUE THREAD

**Issue by dmedine** [sccn/labstreaminglayer#252]
I've added some features and fixed some bugs in the LiveAmp app, and I want to get it it working with the new CMake + AppVeyor features.

I got everything building properly, but there are a couple issues. 

1. What am I to do about the external LiveAmpLib2.dll/lib dependency? I seem to remember some discussion about where the external libs go during the initial development of the CMake infrastructure but I can't find it now. Unfortunately, I can't release the source code for that library, only the binaries. These are very small (333 kB) so I'm not opposed to just sticking them in the repository, but that might not be a can of worms we want to open. 

Also, I can't figure out how to get the installLSL function to copy the dll into the install directory. Please advise, CMake gurus.

2. I had some trouble with the ui_mainwindow.h files. The ones in the repository were generated with Qt4, so they have <QtGui/QApplication> etc. rather than <QtWidgets/QApplication> etc. This means they need to be regenerated. However, the only way I could get the CMake generated projects to re-run UIC on the ui file was to delete the ui_mainwindow.h file, clean the project and rebuild. This worked, but it also rebuilds all of liblsl in the process (even in an out of tree situation). I had to do this 3 or 4 times before I got everything right, so this was pretty annoying from a development point of view.

So, two questions: is there anyway to avoid rebuilding liblsl when cleaning an app project? and is there a simpler way to re-UIC the pertinent .h files (in the context of a Visual Studio project) without deleting and cleaning? If not, this isn't a big deal. It is reasonable to expect a developer to know how to call UIC fromt he command line or whatever.

**Comment by tstenner** [comment]
1. A combination of an [imported library](https://cmake.org/cmake/help/v3.5/command/add_library.html#imported-libraries) with [IMPORTED_LOCATION](https://cmake.org/cmake/help/v3.5/prop_tgt/IMPORTED_LOCATION.html) set? Otherwise you could generate the library with CMake and [export](https://cmake.org/cmake/help/v3.5/command/export.html) the build information, but that's more complicated. To copy the LiveAmpLib2.dll to the directory, you could use `installLSLAuxFiles(LiveAmp LiveAmpLib2.dll Readme.txt etc.)` 

2. Do you have the `mainwindow.ui` in your source set (`add_executable(LiveAmp mainwindow.cpp mainwindow.ui ...`)? After including `LSLAppBoilerplate` CMake should generate `ui_mainwindow.h` automatically as long as it doesn't exist and has a modification time older than `mainwindow.ui`

**Comment by dmedine** [comment]
1. Ok, I'll play around with this and see what makes the most sense.
2. Thanks! I didn't see mainwindow.ui as a source in any of the other cmakelists files. I guess you didn't include them because normally the gui design doesn't change. Glad to know this can be handled elegantly.

**Comment by dmedine** [comment]
Actually, I guess what my question was really about was how to handle the packaging of 3rd party libs. Are we still relying on the python script to grab these off of UCSD's servers? This doesn't feel like a very permanent solution (especially since I will lose my write access to these servers this month).

**Comment by dmedine** [comment]
Also, actually, it turns out that mainwindow.ui was listed as a source all along, so I'm not sure why that wasn't working for me.

**Comment by dmedine** [comment]
So I pushed my commits on this one. I still haven't dealt with the library issue because, as it turns out, my access to sccn's ftp is already gone. I sent Clement a link to my binaries so he could upload them. Everything is working fine so I'll close this issue. I'll return to the library issue when I try to get this onto AppVeyor.
