### ISSUE TITLE
Can't install it for MATLAB

### ISSUE THREAD

**Issue by Apollo22** [sccn/labstreaminglayer#255]
I am on Windows 10 64 and use MATLAB R2017a 64-bit

I first used get_deps.py to get liblsl64.dll. Then I put liblsl64.dll in labstreaminglayer-master\LSL\liblsl-Matlab\bin
Then I used addpath(genpath('$MYPATH$\labstreaminglayer-master\LSL\liblsl-Matlab')). But when I try to use one exemple, I get this:

`Undefined function or variable 'lsl_loadlib_'.`

**Comment by Apollo22** [comment]
I solved it by downloading the folder liblsl-Matlab directly from ftp://sccn.ucsd.edu/pub/software/LSL/SDK/ and using addpath(genpath('$MYPATH$\liblsl-Matlab')) in MATLAB.

It appears that the liblsl64.dll file I got from get_deps.py is bigger. But copying the new file in the previous folder didn't solve the problem.

Do you know which files are necessary in /bin besides liblsl64.dll ? (the bin folder from sccn also has liblsl32.dll, liblsl32.dylib, liblsl64.dylib and liblsl64.so and different files in the mex folder)

**Comment by dmedine** [comment]
The files not ending .dll are libraries for other operating systems. 32 
means compiled for 32 bit and 64, likewise means 64 bit. Apple and Linux 
discontinued 32 bit a long time ago, but Windows maintains it for some 
reason (some compatibility kludge).

Probably the reason the download from SCCN worked has to do with the mex 
(matlab executable) files that it provides. This is actually something 
that needs work because as time goes on, I see this fail more and more 
and I have to rebuild the mex files by hand with different combinations 
of newly compiled versions of the library/matlab.

I'm glad it is working for you.
