### ISSUE TITLE
Error while installing on macOS

### ISSUE THREAD

**Issue by fumiaki-i** [sccn/labstreaminglayer#272]
I had the following problem during the installation on macOS with the command provided (cmake --build . --config Release --target install).

** BUILD FAILED **

The following build commands failed:
	CompileC build/LSL/liblsl/LabStreamingLayer.build/Release/lsl.build/Objects-normal/x86_64/info_receiver.o LSL/liblsl/src/info_receiver.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Does anyone know how to fix this problem?

**Comment by cboulay** [comment]
Can you hope on the LSL #users channel in Slack and I'll see if I can diagnose it?

https://join.slack.com/t/labstreaminglayer/shared_invite/enQtMzA2NjEwNDk0NjA5LWI2MmI4MjBhYjgyMmRmMzg2NzEzODc2M2NjNDIwODhmNzViZmRmMWQyNTBkYzkwNmUyMzZhOTU5ZGFiYzkzMzQ

**Comment by cboulay** [comment]
Problem was solved by using regular `cmake` instead of `ccmake`. I'm not sure what it does under the hood but `ccmake` seems to silently change some variables that affect compilation. While I couldn't reproduce this error exactly, I was able to reproduce a different difference between cmake and ccmake on my system. For now, at least, I'm going to remove ccmake from the INSTALL instructions.
