### ISSUE TITLE
using g.HIamp with LSL

### ISSUE THREAD

**Issue by isirana** [sccn/labstreaminglayer#280]
Can someone explain how to configure the g.HIamp with LSL??

**Comment by cboulay** [comment]
Did you find the g.NEEDaccess app?
Hop on to the [Slack users channel](https://join.slack.com/t/labstreaminglayer/shared_invite/enQtMzA2NjEwNDk0NjA5LWI2MmI4MjBhYjgyMmRmMzg2NzEzODc2M2NjNDIwODhmNzViZmRmMWQyNTBkYzkwNmUyMzZhOTU5ZGFiYzkzMzQ) and I can chat with you about it.

**Comment by cboulay** [comment]
After chatting with the user and getting some screenshots, it turns out that the user was unable to configure the BUILD because they did not have the g.NEEDaccess SDK installed.

Here is a build of the g.NEEDaccess app; it will only work if the g.NEEDaccess SDK is installed. If not already on your system, you may need to install [MSVC redistributable packages for Visual Studio 2015](https://support.microsoft.com/en-ca/help/2977003/the-latest-supported-visual-c-downloads)

[gNEEDaccess.zip](https://github.com/sccn/labstreaminglayer/files/1811466/gNEEDaccess.zip)
