### ISSUE TITLE
cmake links qt for msvc2017 when -G "Visual Studio 13 2015 [arch]" flag is given

### ISSUE THREAD

**Issue by dmedine** [sccn/labstreaminglayer#330]
Maybe it does this for other values for -G as well. This doesn't seem to matter since the infrastructure is currently not copying the dlls into the installation directories (at least not on my setup) but this is definitely not desirable.

I get this at least with LiveAmp and LabRecorder.

**Comment by cboulay** [comment]
Did you get the warning that "You didn't specify a Qt5_DIR. I'm guessing it's ${Qt5_DIR}. If you are building Apps that require Qt and if this is wrong then please add the correct dir:"?

Here is the code in the [super repo](https://github.com/labstreaminglayer/liblsl/blob/master/LSLCMake.cmake#L212-L281) and [this repo](https://github.com/sccn/labstreaminglayer/blob/master/LSL/liblsl/LSLCMake.cmake#L219-L281).

If you didn't get that warning then that means that Qt5_DIR is set.

And it absolutely should be copying the dlls, but only when you build the INSTALL target. Just building LabRecorder or LiveAmp itself won't trigger it. If you are building the INSTALL target but it still isn't copying the dlls, this might be because of the Qt weirdness; the dll copying is actually performed by a qt program.

**Comment by dmedine** [comment]
Your exactly right Chadwick. I was pointing to the wrong Qt version.
