### ISSUE TITLE
No clock offsets were available when using LSL and GUSBAmp

### ISSUE THREAD

**Issue by ali-sig-pro** [sccn/labstreaminglayer#337]
I was wondering if you may guide how to deal with the issue 'No clock offsets were available for stream...'.

I use GUSBAmp and LabRecord from LSL to record EEG from g.USBamp. When importing the recordings with xdf extension using ImportingRecordingsInMatlab to Matlab, I face with the warning message 'No clock offsets were available for stream...'. I use at all one computer for EEG recording and also streaming LSL.
Does 'No clock offsets available' mean that the recordings were already messed up during recording because of something seriously wrong with timing and clock offset such that the recordings are not reliable anymore? 
Any suggestion to dig/solve this issue?

Many thanks,

**Comment by dmedine** [comment]
When LabRecorder records data, it periodically checks the clock offset 
between the clock on the computer running LabRecorder and all the 
computers hosting LSL clients from which it is recording. When the data 
is loaded offline, these offsets are used to synchronize the various 
data streams. (I have written that sentence so many times, I should have 
it in a text file so that I can copy and paste it.)

Not getting clock offsets in your data file is a bug. But, since you are 
using only one computer, the clock offsets that /should/ have been 
recorded are very, very, very tiny (smaller than a microsecond, most 
likely). In you case, you don't need to worry about this warning. If you 
are streaming data from different computers across a network, you cannot 
synchronize without the clock offset data. On a local host it is irrelevant.

I am going to close this issue and re-open it under a different title. 
The reason is that I don't believe this has anything to do with the 
g.USBamp connector, but rather it is a problem with either LabRecorder 
or liblsl.
