### ISSUE TITLE
Building on Mac OS 10.14.6 with macports

### ISSUE THREAD

**Issue by colmconn** [sccn/labstreaminglayer#35]
Just an FYI, to get this to build on MAC OS 10.14.6 with the macports I followed the build instructions for the MAC but ran in to errors like
```
CMake Warning (dev) in Apps/Examples/CMakeLists.txt:
  AUTOGEN: No valid Qt version found for target ReceiveDataC.  AUTOMOC,
  AUTOUIC and AUTORCC disabled.  Consider adding:

    find_package(Qt<QTVERSION> COMPONENTS Widgets)

  to your CMakeLists.txt file.
```
To fix these issues I added `find_package(Qt5 COMPONENTS Widgets)` at Line 11 in labstreaminglayer/CMakeLists.txt. The project then appears to build correctly.

**Comment by tstenner** [comment]
This warning is harmless, but tricky to remove. Basically, we tell CMake to run moc, uic und rcc *if needed*. liblsl and the examples don't use Qt, so the warning says "I can't run moc, uic and rcc because you haven't imported Qt", but since it's not needed everything still builds.

We can't get rid of the warning, because by the time we find out an app uses Qt it's too late and we can't import Qt by default because then the warning would complain about Qt not being found.

**Comment by cboulay** [comment]
@tstenner , Any objections to adding `QUIET` to the `find_package` arguments?

**Comment by tstenner** [comment]
> Any objections to adding QUIET to the find_package arguments?

Yes, it wouldn't work :-)

The most promising solution is to require apps to set the `CMAKE_AUTO*` variables themselves, so I added them in all apps in the repository.
After a grace period, we can drop them from `LSLCMake.cmake`.

**Comment by tstenner** [comment]
I found a different solution (https://github.com/sccn/liblsl/commit/dfa0fbdf6d73c908384c832760cbf516aaebe254).
