### ISSUE TITLE
library binaries not on github?

### ISSUE THREAD

**Issue by gleslie** [sccn/labstreaminglayer#38]
Sorry if I'm missing something! The library binaries are missing from liblsl/bin. Is there a new protocol that we're supposed to track those down on the ftp (as referenced in the readme)? Just trying to make sure I have the lastest versions.

**Comment by dmedine** [comment]
When you clone the repository, you get a python script called 
get_deps.py. This will download and put all the libraries and binaries 
in their proper places in your copy of the repository. Also, if you push 
a clone, the .gitignore, will prevent any compiled code from getting 
pushed. This is because git gets slowed down a lot with lots of binaries 
hanging around. The actual executables (Apps) however will need to be 
built. The repository attempts to be purely source code.

There ought to be a link to the ftp, but I see that it is missing from 
the title page.
ftp://sccn.ucsd.edu/pub/LSL/
if you just want all the apps etc. go for the ftp version. This probably 
needs to be updated a little bit, but everything there should be working 
-- for Windows 7, anyway.
