### ISSUE TITLE
Sending Data from one Pc to another PC useing Labrecorder and LSL4Unity

### ISSUE THREAD

**Issue by AkashSh** [sccn/labstreaminglayer#46]
Dear Chad,

hi my name is Akash and I am  student in Germany currently I am useing your C-File for LSL4Unity for a Thesis. But actually have a problem i want to stream a trigger from Unity to Labrecorder but on a other PC.

That means I want to send Data from Unity from one PC to Labrecorder which is runnig on another PC. The Problem is I only can recive Data from Unity on the same PC on which Unity is runnig so actually Labrecorder on the other PC does not show me the Unity Data i want to recive.

i hope you really can help me out.

Best regards
Akash

**Comment by cboulay** [comment]
Hi Akash,

Normally I would close this issue and ask you to open a new issue in the correct repository (i.e., https://github.com/labstreaminglayer/LSL4Unity). However, I suspect that this problem is not specific to Unity.

On the PC that normally runs Unity, please run another stream. If it has a microphone then the easiest might be the AudioCapture app [here](https://github.com/labstreaminglayer/App-AudioCapture/releases). See if that shows up on the same PC's LabRecorder, and if it shows up on the "other PC".

If that also doesn't show up, then it's not a Unity-specific problem. Take a look https://labstreaminglayer.readthedocs.io/info/network-connectivity.html , including following the link to the configuration file settings under the sub-heading "Customizing Network Features of LSL" .

**Comment by AkashSh** [comment]
Oh sorry actually i don't use Github that often I just clicked the Link you send me previously and started a issue there. Sorry for that

I will try your advice actually unity can send data trough Network but It’s only possible with Python I have script for that.



Am 27.01.2020 um 16:29 schrieb Chadwick Boulay <notifications@github.com>:

﻿

Hi Akash,

Normally I would close this issue and ask you to open a new issue in the correct repository (i.e., https://github.com/labstreaminglayer/LSL4Unity). However, I suspect that this problem is not specific to Unity.

On the PC that normally runs Unity, please run another stream. If it has a microphone then the easiest might be the AudioCapture app here<https://github.com/labstreaminglayer/App-AudioCapture/releases>. See if that shows up on the same PC's LabRecorder, and if it shows up on the "other PC".

If that also doesn't show up, then it's not a Unity-specific problem. Take a look https://labstreaminglayer.readthedocs.io/info/network-connectivity.html , including following the link to the configuration file settings under the sub-heading "Customizing Network Features of LSL" .

**Comment by cboulay** [comment]
There hasn't been any follow-up for 2 months so I'm going to close the issue. Please feel free to re-open it and add additional information if you're still having difficulties.
