### ISSUE TITLE
Only supported timeouts are 0 and forever

### ISSUE THREAD

**Issue by ulatekh** [sccn/labstreaminglayer#48]
In consumer_queue::pop_sample(), in LSL/liblsl/src/consumer_queue.cpp, if the provided timeout is > 0, it loops forever, sleeping for 1 millisecond between attempts to pop a sample from the internal buffer.

The fix is simple, and I can do it quickly; I was wondering if there was any good reason for not supporting any timeouts except 0 and forever.

Since my intention is to pull samples from the C# interop layer, I can't use the boost::thread::interrupt() method to stop a pull-sample thread, and the thread_interrupted exception isn't getting marshaled in the C# interop layer, so I probably can't use that method anyway. So I need a timeout to make it work.

Later, I'll ask why consumer_queue::pop_sample() does a busy loop, instead of something more CPU efficient (like a client-set boost::function based callback in lsl::data_receiver::data_thread()), but one step at a time.

**Comment by chkothe** [comment]
Hi ulatekh, good catch.

Actually the first implementation of the the queue used a boost condition
variable and associated timeout, but it turned out that this implementation
wasn't sufficient for the minimum-latency / high-bandwidth throughput that
we wanted for liblsl (needs to be <=1ms latency and support >2 million
samples/second), you can see it here
<https://code.google.com/p/labstreaminglayer/source/diff?spec=svnbed90a7614ea48540dda6204d011320e02fc0b34&r=8a5d19b988304a404351fbe01ad5c3c36509f2b2&format=side&path=/LSL/liblsl/src/consumer_queue.cpp&old_path=/LSL/liblsl/src/consumer_queue.cpp&old=6822c98b64d391c2a0036c3e49f49dfbd747e620>.
I don't recall specifics right now, but it might have been CPU overhead or
sleep granularity, so it got replaced by the sleep loop (the current
version is very efficient because the pop call is extremely fast and the
sleep occurs only when there's a stall), but it looks like I didn't get
around to re-adding a check for arbitrary timeouts...

If you make a pull request, I think a good approach would be to try to pull
a sample first (fast path) and only if that fails, read the clock and do
the while loop with an extra check for timeout expiration, because the
clock functions are pretty slow. I suppose boost::chrono should have a
suitable clock for that.

Christian

**Comment by ulatekh** [comment]
My suggested fix is simpler than using a clock:

diff --git a/LSL/liblsl/src/consumer_queue.cpp b/LSL/liblsl/src/consumer_queue.cpp
index 53504e9..3b4241f 100644
--- a/LSL/liblsl/src/consumer_queue.cpp
+++ b/LSL/liblsl/src/consumer_queue.cpp
@@ -51,8 +51,10 @@ sample_p consumer_queue::pop_sample(double timeout) {
 	if (timeout <= 0.0) {
 		buffer_.pop(result);
 	} else {
-		while (!buffer_.pop(result))
+		while (!buffer_.pop(result) && timeout > 0.0) {
 			boost::this_thread::sleep(boost::posix_time::milliseconds(1));
+			timeout -= 0.001 /* 1 millisecond */;
+		}
 	}
 	return result;
 }

I'll make this a pull request at some point.

**Comment by chkothe** [comment]
Hey, that's pretty nifty! Though one issue would be that the duration of sleep isn't necessarily exactly one millisecond (and the extra code in the while loop will make it probably a little more than one ms), so there can be considerable drift accumulating over multiple loop cycles on some OSes. Now, I do like the fact that there's no clock readout involved, but maybe when we offer timeouts we should make it so that the timeout is being met within a ms (because users might rely on it being accurate to drive the timing of other parts of their code).

**Comment by ulatekh** [comment]
I may have incorrectly assumed that the pull_sample() timeout had to be precise. If so, I can write a more complex version. Then we'd probably have to change the 1-ms sleep to be more precise. We could go quite far down the rabbit hole on this one.

In any case, you know what the issue is, what causes it, and what one fix might be.

**Comment by ulatekh** [comment]
https://github.com/sccn/labstreaminglayer/pull/51 is my fix for this problem. It also fixes the missing timeout_error exception.
