### ISSUE TITLE
Use LSL with BrainMaster Discovery 24E which is not listed in Supported Devices Section

### ISSUE THREAD

**Issue by mubin986** [sccn/labstreaminglayer#50]
Hello,
This is Mubin from Bangladesh. I use BrainMaster Discovery 24E device to collect EEG data on my computer. I want to use LSL with my device. But, I didn't find my device listed on the supported devices section here: https://labstreaminglayer.readthedocs.io/info/supported_devices.html

I also didn't find any support email/contact from which I can get any support to connect my device with LSL.

This is the link for BrainMaster Discovery 24E: https://www.brainmaster.com/product/discovery-24e

Thank you.

**Comment by cboulay** [comment]
For someone to create an application they would need the hardware and access to the SDK. I couldn't find the SDK on the website and it looks like their software model is incompatible with them releasing an SDK, but I'm just speculating there.

You'll have to ask the manufacturer.

I'm closing this issue because there is nothing to be done from our end. If you do get access to the SDK then you should read the LSL documentation for help getting started creating your own application.
