### ISSUE TITLE
LSL using Polar H10 heart rate monitor

### ISSUE THREAD

**Issue by sunshineinsandiego** [sccn/labstreaminglayer#69]
Hi - I'm attempting to align an EEG LSL stream from a MUSE headset with ECG data from a Polar H10. Is it possible to use LSL to acquire data from a Polar H10? Hoping to build a standardized analysis pipeline that uses LSL across a variety of biosensing devices and would appreciate your advice! Thanks much.

**Comment by agricolab** [comment]
It seems Polar offers a SDK for the H10, see https://www.polar.com/en/developers/sdk  and https://github.com/polarofficial/polar-ble-sdk so that should be doable. And a quick github search uncovered this repo: https://github.com/markspan/PolarBand2lsl based on https://towardsdatascience.com/creating-a-data-stream-with-polar-device-a5c93c9ccc59

so, looks like yes

**Comment by sunshineinsandiego** [comment]
Got it, thanks for the heads up. Didn't see that hit on github. Will try.
