### ISSUE TITLE
git bloat

### ISSUE THREAD

**Issue by cboulay** [sccn/labstreaminglayer#80]
I can't pinpoint when it started, but I noticed recently that cloning labstreaminglayer takes a lot longer than it used to (but not as long as google code days). The clone that I completed just a minute ago downloaded 265.89 MiB.

```
git clone https://github.com/sccn/labstreaminglayer.git
Cloning into 'labstreaminglayer'...
remote: Counting objects: 44937, done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 44937 (delta 4), reused 0 (delta 0), pack-reused 44913
Receiving objects: 100% (44937/44937), 265.89 MiB | 580.00 KiB/s, done.
Resolving deltas: 100% (23887/23887), done.
Checking connectivity... done.
```

 `du -hs <dirname>` gives me 401M for `labstreaminglayer`, within which we get 59M for `Apps`, 74M for `LSL`, and 268M for `.git`. (this is all before I do a get_deps)

My guess is that some binaries are being tracked that previously were not.

I followed some steps [found on the web](http://blog.jessitron.com/2013/08/finding-and-removing-large-files-in-git.html) to get a list of large-ish files in the history. See attached. There are a bunch of tools on the web for dealing with this problem. If you decide to cleanup the repo, downstream repos will no longer be compatible so they will have to do a new fork or a new clone. While this is not desirable, it's certainly better to do it sooner than later.
[large_files.txt](https://github.com/sccn/labstreaminglayer/files/117624/large_files.txt)

**Comment by dmedine** [comment]
Thanks for noticing this. This is definitely on me for not keeping 
things clean. I will see what I can do about reducing the bloat here.
Cheers,
David

**Comment by dmedine** [comment]
OK, so I cleaned the lib files out of here. Everyone should re-clone LSL 
in order to cash in on this. I followed the blog post suggested by 
Chadwick 
(http://blog.jessitron.com/2013/08/finding-and-removing-large-files-in-git.html) 
and then went to ye olde BFG instructions: 
https://rtyley.github.io/bfg-repo-cleaner/ for how to push these changes 
upstream. The crucial lines (if anyone is interested) are:

|git reflog expire --expire=now --all && git gc --prune=now --aggressive|||

||and

git push --force origin master

These will clean out all the junk cleared out through jessitron's method.

What puzzles me is that after re-cloning the repository and checking the 
size of the directories, it was the Apps folder (15M, down from 59!), 
not the .git folder that got reduced. Perhaps there is some way to 
reduce the size of .git further. In any case, the new large_files.txt 
doesn't have all the .zips and libs in it anymore.

I hope I didn't fry anything here, but I'm pretty sure I didn't and I 
can revert the repository in case I did. I also made a local backup just 
to be safe.

**Comment by cboulay** [comment]
The blog post I referenced isn't a full solution. If you read in the comments then someone references another script [found here](https://stubbisms.wordpress.com/2009/07/10/git-script-to-show-largest-pack-objects-and-trim-your-waist-line/).

I ran that and it found some more items in older commits. It looks like there's another 60MB of savings to be had.

```
All sizes are in kB's. The pack column is the size of the object, compressed, inside the pack file.
size   pack   SHA                                       location
96982  22482  2a83b3ff420579bf372258f59be601fefb18b3e3  LSL/liblsl-iOS/iOSboost/boost/ios/boost.a
53629  8986   0bb8c19f8a405dc9860c5ce2d5e3a7837ce92a73  LSL/liblsl-iOS/Intermediates/liblsl-iOS.build/Debug-iphoneos/liblsl.build/Objects-normal/armv7/liblsl
36587  6807   055f89bc7403c809dc6c6c3c59016cd8f442f798  Apps/Embarcadero                                                                                       XE/Hotspots/Debug_Build/hotspots.pch
21641  4175   317a9badae4b28113e41e9fc55d6b3b137da482b  Apps/PupilPro/zmq/bin/mac/libzmq.a
16663  6500   dc0149148c8739189ce8b0945233896f7195f661  LSL/liblsl-iOS/Intermediates/liblsl-iOS.build/Debug-iphoneos/liblsl.build/Objects-normal/arm64/liblsl
14969  686    817f1e43c9ec583418290dac9b3c6072389464ec  LSL/liblsl-iOS/Intermediates/liblsl-iOS.build/Debug-iphoneos/liblsl.build/dgph
14488  4647   9c9552b86d547b9b2425918b70957f492bca3447  Apps/SMI                                                                                               Eyetracker/Legacy-SDK/QtGuid4.dll
11584  2637   c6f8a93357ab6881f24b6bb183fd04881b090aba  Apps/Embarcadero                                                                                       XE/bin/hotspots.tds
8946   3742   53cc4113313af56712a5ca171a181a37dc0050ea  Apps/Embarcadero                                                                                       XE/bin/opencv_ffmpeg243.dll
8458   8460   e67b59913a1469a106ecc30f2fcbbaeca6600a5d  Apps/BioSemi/drivers-win32_64.zip
```

**Comment by cboulay** [comment]
[This](https://github.com/cmaitchison/git_diet) looks nice and simple.

**Comment by chkothe** [comment]
I think it would be good to check with Luca Mussi before we pull the
trigger on that, just in case he's currently meticulously rebuilding his
pull requests for resubmission (because if we nuke them again we have one
less contributor). Either he holds off for another day or so while the repo
gets another shave or we wait for & merge his PRs and then do it. We could
also roll back to 48 hours ago by calling customer service, then merge the
PRs, and then nuke the history. What do you guys think?

Christian

**Comment by cboulay** [comment]
If you want to wait then I can submit my pull requests. They are ready to go. (they are very small)

**Comment by chkothe** [comment]
Actually Luca's changes are very simple, I can manually reapply them. So
let me do that right now quickly, and in the meantime you can push up your
PRs & we can merge, so we have everything in there. Then we'd be ready to
drop the bomb ;)

**Comment by dmedine** [comment]
I think this is the way to go. Christian, let me know when you push 
Luca's code up.

**Comment by chkothe** [comment]
Ok, I'm done with Luca's stuff. In meetings from now on, so maybe you want
to handle Chad's PRs.

Christian

**Comment by dmedine** [comment]
Testing those on Windows 7 as we speak...

Thanks, Christian.

**Comment by dmedine** [comment]
OK, Chadwicks pulls are tested and merged. Christian's can wait and Luca's got entered by hand. I am going to have to postpone the cleansing rain until next week due to some computing infrastructure issues at the lab that are too complicated and trivial to explain. Suffice to say, my hands are tied for the moment. Should be fine by Monday.

**Comment by dmedine** [comment]
I'm not sure what happened, but now a fresh clone has a .git size of 516Mb! I am pulling the trigger on another round of bombs as we speak -- using the git_diet approach. Hopefully all will be well.

**Comment by dmedine** [comment]
Alright, so I ran the scripts Chadwick provided a link to earlier ([here](https://github.com/cmaitchison/git_diet)) then ran git remote prune origin. After inspecting a fresh clone, the .git foler is back at 276Mb, but my .git in the local clone that I ran the pruning script on has a .git of only 173Mb. I don't quite understand why this extra cruff seems to keep coming into the .git directory.
