### ISSUE TITLE
liblsl-Android

### ISSUE THREAD

**Issue by dmedine** [sccn/labstreaminglayer#90]
I have not been carefully following the discussions about lsl and Android, but I think we have some reorganizing to do here. I see the existence of liblsl/project/android-vs2013 and liblsl-Android as redundant. I would propose moving all things lsl-android to a single location, specifically liblsl-Android. 

Thoughts?

**Comment by chkothe** [comment]
I think that's a good idea. May be best to check back with Matthew just in
case he's prepping an update right now. My last interaction with him re
Android update was 2 or so days ago (on the thread with Zijing). I'd love
to see the new Java API make it into github for Android. I've not yet
tested it personally though (although Ole did), so best to run a few
examples on there first to confirm that it's OK.

**Comment by mgrivich** [comment]
They are not redundant. Android-vs2013 is based on visual studio, while 
liblsl-Android is more "raw" and only uses tools from google's sdk. If 
requested, I can move the visual studio package though.

**Comment by mgrivich** [comment]
I've put the transition to the new java api on my to-do list, but it may 
be a bit before I get to it.

**Comment by chkothe** [comment]
Very cool! I might also join the Androis party at some point in the near
future (e.g., additional testing), just need to get a bunch of other tasks
off my plate.

**Comment by dmedine** [comment]
Matthew's right, of course. Redundant is not the right word. However, yes, let's move the vs project into the liblsl-Android part of the directory tree,

**Comment by mgrivich** [comment]
I will do this. Some paths in the project have to be updated or it will 
not build.

**Comment by chkothe** [comment]
So I've looked a little into the situation around the Android Studio port
for liblsl. Here's what I gathered (most of which is known to Matthew I
think):
* the whole Eclipse-based development process for Android is deprecated in
favor of Android Studio (which is of course a good thing since AS is much
nicer)
* with that, also the entire official NDK documentation as it relates to
Eclipse (http://developer.android.com/ndk/guides/setup.html) is deprecated
* the old Android.mk and Application.mk files still work and it's possible
to invoke them from Gradle (the build system used by AS), but that's a
pretty ugly stop-gap solution at best
* there's some support for building native code with Gradle that's able to
replace the old Makefile-based system
* that system is however being replaced by something that's currently in
experimental state (
http://tools.android.com/tech-docs/new-build-system/gradle-experimental)
and is very likely still going to change
* there's presumably going to be some neat and canonical way to distribute
3rd party native library binaries ("prebuilt libraries") and a
corresponding way to integrate them into the project, but that's neither
looking final nor is it really documented, and there aren't exactly many
precedents around
* much of this was, I think, supposed to be out of beta by now, but it
seems that progress has been lacking, and the official docs are incomplete
at best

So I think the course of action would have to be to hold off and wait until
they stabilize the native build process for AS, and then we can jump in and
make a neat little redistributable package for the various ABIs plus
sources to rebuild it yourself and an example project. Comments welcome.

**Comment by mgrivich** [comment]
Yes, Eclipse for Android is deprecated. Android Studio is the Google 
sanctioned replacement. The last time I checked, its native support was 
weak. However, nVidia makes CodeWorks for Android 
(https://developer.nvidia.com/codeworks-android) which is a plug in for 
Visual Studio and good for native code. Currently, I am using Android 
Studio to develop on the Java side, and CodeWorks to develop on the 
native side. It's messy, but virtually everything about Android 
development, especially native development, is messy.

I used this procedure to make PsychLab 101 for Android 
(https://play.google.com/store/apps/details?id=com.neurobs.psychlab101&hl=en) 
and am currently developing Presentation (Neurobehavioral Systems' 
flagship product) for Android.

I have integrated LSL with Presentation for Android, but it is not 
publicly available yet.
